// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjjzwfggawyifrhvvcfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhqanp3ZmdnYXd5aWZyaHZ2Y2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDA1OTksImV4cCI6MjA3MDQ3NjU5OX0.UsKn5lbHmI8iX-u3PHD3pTQhX0KcRZ6AnF596MSwfFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});